# Generated by Django 2.2.3 on 2019-09-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=80)),
                ('value_1', models.FloatField(default=0)),
                ('value_2', models.FloatField(default=0)),
                ('value_3', models.FloatField(default=0)),
                ('value_4', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'example',
            },
        ),
    ]
